name: CI-Tests

on:
  workflow_dispatch:
  pull_request:

permissions: read-all

env:
  GO_VERSION: 1.17.x

jobs:
  unit-tests:
    name: Run unit tests
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 #v2.4.0
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab #v2.1.5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run Go tests
        run: go test ./...
